[package]
name = "flow-cli"
version.workspace = true
edition.workspace = true

[dependencies]
flow-core = { path = "../core" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
miette.workspace = true
thiserror.workspace = true
inquire = "0.7"
