[package]
name = "flow-core"
version.workspace = true
edition.workspace = true

[dependencies]
loro = "1.0"
chrono = "0.4"
confy = "2.0.0"
serde.workspace = true
toml.workspace = true
uuid.workspace = true
miette.workspace = true
thiserror.workspace = true
